#env_name: MountainCar-v0
env_name: Pendulum-v1
#env_name: CartPole-v1
render: false

buffer_size: 500000
batch_size: 64

epoch_length: 5000
max_epochs: 200
step_start_train: 2000
train_freq: 50

soft_update_factor: 0.995
hidden_sizes: [32, 32]
lr_actor: 5e-4
lr_critic: 1e-3
device: cpu

gamma: 0.99
epsilon: 0.5

save_per: 10

test: false