#env_name: MountainCar-v0
#env_name: Pendulum-v1
env_name: CartPole-v1
render: false

buffer_size: 5000
batch_size: 32

epoch_length: 5000
max_epochs: 200
step_start_train: 2000
train_freq: 50

hidden_sizes: [32]
lr: 1e-2
lr_actor: 5e-3
lr_critic: 4e-2
device: cpu

gamma: 0.95
epsilon: 0.5

save_per: 10

test: false