#env_name: MountainCar-v0
env_name: Pendulum-v1
#env_name: CartPole-v1
render: false

buffer_size: 500000
batch_size: 64

epoch_length: 5000
max_epochs: 300
step_start_train: 2000
train_freq: 50

soft_update_factor: 0.999
hidden_sizes: [64]
lr_actor: 1e-4
lr_critic: 2e-4
device: cpu

gamma: 0.99
epsilon: 0.5

save_per: 10

test: false